import { useEffect, useState } from 'react'
import { Empty, Field, Loading, PhotoPicker, Thumb } from '../components/ui'
import { supabase } from '../lib/supabase'

type Release = {
  id:string; status:string; receipt_code:string; authorized_pickup_name:string; scheduled_for?:string|null
  notes?:string|null; evidence_id:string; released_at?:string|null; customer_acknowledgment_name?:string|null
  clients?:{name?:string|null}|null
  release_items?:Array<{id:string;bottle_id:string;status:string;bottles?:{label_photo_path?:string|null;wines?:{name?:string|null;vintage?:number|null;producer?:string|null}|null;slots?:{shelf?:number|null;position?:number|null;racks?:{name?:string|null}|null}|null}|null}>
}

export function AdminReleases(){
  const [rows,setRows]=useState<Release[]|null>(null),[selected,setSelected]=useState<string|null>(null)
  const [form,setForm]=useState({idType:'Licencia',idLast4:'',name:'',pickupPhoto:'',bottlesPhoto:'',ack:false})
  const [busy,setBusy]=useState(false),[error,setError]=useState('')
  const load=async(prefer?:string)=>{const {data,error:e}=await supabase.from('release_requests').select('*,clients(name),release_items(*,bottles(label_photo_path,wines(name,vintage,producer),slots(shelf,position,racks(name))))').order('created_at',{ascending:false});if(e)setError(e.message);const list=(data??[]) as Release[];setRows(list);setSelected(prefer??selected??list.find(x=>x.status!=='completed'&&x.status!=='cancelled')?.id??list[0]?.id??null)}
  useEffect(()=>{void load()},[])
  const request=rows?.find(x=>x.id===selected)??null,complete=request?.status==='completed',items=request?.release_items??[]
  const startProcessing=async()=>{if(!request)return;setBusy(true);setError('');const {error:e}=await supabase.rpc('start_release_processing',{p_request_id:request.id});setBusy(false);if(e){setError(e.message);return}await load(request.id)}
  const finalize=async()=>{if(!request)return;setBusy(true);setError('');const {error:e}=await supabase.rpc('finalize_release_receipt',{p_request_id:request.id,p_id_type:form.idType,p_id_last4:form.idLast4,p_customer_name:form.name,p_pickup_photo_path:form.pickupPhoto,p_bottles_photo_path:form.bottlesPhoto,p_acknowledged:form.ack});setBusy(false);if(e){setError(e.message);return}setForm({idType:'Licencia',idLast4:'',name:'',pickupPhoto:'',bottlesPhoto:'',ack:false});await load(request.id)}
  const pending=rows?.filter(x=>!['completed','cancelled'].includes(x.status))??[],closed=rows?.filter(x=>x.status==='completed')??[]
  return <div className="intake-desk release-desk">
    <div className="intake-title"><span className="landing-kicker">Cadena de custodia</span><h1>Entregar botellas</h1><p>Confirma identidad, fotografía la entrega y genera el recibo antes de liberar inventario.</p></div>
    <div className="intake-workspace"><aside className="intake-queue"><h2>Pendientes <span>{pending.length}</span></h2>{rows===null?<Loading/>:pending.length===0?<p className="muted small">No hay salidas pendientes.</p>:pending.map(r=><button key={r.id} className={r.id===selected?'active':''} onClick={()=>setSelected(r.id)}><b>{r.clients?.name||'Cliente'}</b><small>{r.receipt_code} · {r.release_items?.length||0} botella(s)</small></button>)}{closed.length>0&&<><h2 className="closed-title">Completadas</h2>{closed.slice(0,8).map(r=><button key={r.id} className={r.id===selected?'active':''} onClick={()=>setSelected(r.id)}><b>{r.clients?.name||'Cliente'}</b><small>{r.receipt_code} · entregada</small></button>)}</>}</aside>
      <main className="intake-panel">{!request?<Empty/>:<><div className="intake-panel-head"><div><small>{request.receipt_code}</small><h2>{request.clients?.name}</h2><p className="muted small">Recoge: {request.authorized_pickup_name}{request.scheduled_for?` · ${new Date(request.scheduled_for).toLocaleString('es-PR')}`:''}</p></div><span className={`badge ${request.status}`}>{{requested:'Solicitada',processing:'Preparando',completed:'Entregada',cancelled:'Cancelada'}[request.status]||request.status}</span></div>
        <div className="release-summary"><strong>{items.length}</strong><span>botella{items.length===1?'':'s'} solicitada{items.length===1?'':'s'}</span></div>
        <div className="release-bottles">{items.map(item=>{const b=item.bottles,w=b?.wines,s=b?.slots;return <article key={item.id}><Thumb path={b?.label_photo_path} label={`${w?.name||'Vino'} ${w?.vintage||''}`}/><div><b>{w?.name||'Vino'} {w?.vintage||''}</b><small>{w?.producer||'Productor no indicado'}</small><span>{s?.racks?.name?`${s.racks.name} · S${s.shelf} · P${s.position}`:'Por ubicar'}</span></div></article>})}</div>
        {request.notes&&<div className="info">Nota del cliente: {request.notes}</div>}
        {complete?<section className="intake-receipt"><span>✓</span><div><small>Recibo de salida final</small><h3>{request.receipt_code}</h3><p>{items.length} botella(s) entregadas a {request.customer_acknowledgment_name}</p><code>{request.evidence_id}</code><button className="btn secondary sm no-print" onClick={()=>window.print()}>Imprimir recibo</button></div></section>:<section className="intake-confirm">{request.status==='requested'&&<div className="release-prep"><div><h3>Primero prepara la orden</h3><p>Cambia el estado para que el cliente sepa que sus botellas se están buscando y verificando.</p></div><button className="btn secondary" disabled={busy} onClick={startProcessing}>{busy?'Actualizando…':'Comenzar preparación'}</button></div>}<h3>Confirmar entrega</h3><p>Completa esta evidencia con la persona presente. Guarda solamente los últimos cuatro caracteres de su identificación.</p><div className="grid2"><Field label="Tipo de identificación"><select value={form.idType} onChange={e=>setForm({...form,idType:e.target.value})}><option>Licencia</option><option>Pasaporte</option><option>Otra identificación</option></select></Field><Field label="Últimos 4 caracteres"><input maxLength={4} autoCapitalize="characters" value={form.idLast4} onChange={e=>setForm({...form,idLast4:e.target.value.replace(/[^a-z0-9]/gi,'').slice(0,4)})}/></Field></div><Field label="Nombre de quien recibe"><input autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><div className="intake-photos"><Field label="Foto de persona con identificación"><PhotoPicker path={form.pickupPhoto} prefix={`releases/${request.id}/pickup`} onUploaded={path=>setForm({...form,pickupPhoto:path})}/></Field><Field label="Foto de todas las botellas entregadas"><PhotoPicker path={form.bottlesPhoto} prefix={`releases/${request.id}/bottles`} onUploaded={path=>setForm({...form,bottlesPhoto:path})}/></Field></div><label className="terms-check"><input type="checkbox" checked={form.ack} onChange={e=>setForm({...form,ack:e.target.checked})}/><span>La persona presente confirma que recibió las botellas listadas y en la condición fotografiada.</span></label><button className="btn intake-final" disabled={busy||form.idLast4.length!==4||form.name.trim().length<3||!form.pickupPhoto||!form.bottlesPhoto||!form.ack} onClick={finalize}>{busy?'Finalizando…':`Confirmar entrega de ${items.length} botella${items.length===1?'':'s'}`}</button></section>}
      </>}</main></div>{error&&<div className="error intake-error">{error}</div>}
  </div>
}
