import { Link } from 'react-router-dom'

const samples=[
  {name:'Reserva 1926',meta:'Robusto · Nicaragua',place:'Humidor A · G1 · E02',price:'$22',image:'/images/cigar-reserva-v2.webp'},
  {name:'Maduro Selección',meta:'Torpedo · Dominicana',place:'Humidor A · G2 · E03',price:'$19',image:'/images/cigar-maduro-v2.webp'},
  {name:'Connecticut Privada',meta:'Toro · Honduras',place:'Humidor A · G3 · E04',price:'$14',image:'/images/cigar-connecticut-v2.webp'},
]

export function Demo(){return <div className="demo-page"><header className="public-nav"><Link to="/site" className="public-brand"><img src="/icon.svg" alt=""/><span>CigarrosPR</span></Link><Link className="btn sm" to="/login?signup=1">Crear cuenta</Link></header><main className="demo-shell"><div className="demo-head"><span className="eyebrow">Demostración</span><h1>Tu humidor, claro y visual.</h1><p>Cada foto corresponde a su ficha, etiqueta y ubicación. Estos datos son de ejemplo.</p></div><div className="demo-stats"><article><small>En humidor</small><b>32</b><span>piezas y cajas</span></article><article><small>Valor registrado</small><b>$2,480</b><span>colección</span></article><article><small>Ambiente</small><b>69% HR</b><span>70°F</span></article></div><div className="demo-grid"><section className="demo-inventory"><div className="row between"><h2>Mi colección</h2><span className="badge">Ejemplo</span></div>{samples.map(x=><article key={x.name}><img src={x.image} alt={`Etiqueta de ${x.name}`}/><div><small>{x.meta}</small><b>{x.name}</b><span>{x.place}</span></div><strong>{x.price}</strong></article>)}</section><section className="demo-rack"><span className="eyebrow">Ubicación</span><h2>Humidor A</h2><p>32 de 50 espacios ocupados</p><div className="demo-slots">{Array.from({length:30},(_,i)=><i className={i<19?'full':''} key={i}>{i+1}</i>)}</div><small>Selecciona un espacio para ver su foto y ficha.</small></section></div><Link className="btn public-cta demo-final" to="/login?signup=1">Crear mi colección</Link></main></div>}
