import { Link } from 'react-router-dom'

const plans=[
  {name:'Digital',price:'24.99',tag:'Organiza tu colección',items:['Catálogo personal','Valor de colección','Historial y notas','Acceso desde cualquier dispositivo']},
  {name:'Reserva',price:'120',tag:'Tu espacio en nuestro humidor',featured:true,items:['Hasta 40 piezas o cajas','Ubicación exacta','Control de temperatura y humedad','Solicitudes de entrada y retiro']},
  {name:'Colección',price:'175',tag:'Para coleccionistas',items:['Hasta 100 piezas o cajas','Atención prioritaria','Inventario y valoración','Acceso anticipado a ofertas']},
]
export function Landing(){return <div className="public-site">
  <header className="public-nav"><Link to="/" className="public-brand"><img src="/icon.svg" alt=""/>CigarrosPR</Link><nav><a href="#membresias">Membresías</a><a href="#como">Cómo funciona</a><Link to="/demo">Demo</Link><Link className="btn sm" to="/login">Entrar</Link></nav></header>
  <main>
    <section className="cigar-hero"><div><span className="eyebrow">Humidor privado · Puerto Rico</span><h1>Tu colección de cigarros, cuidada y siempre localizada.</h1><p>Inventario digital, almacenamiento controlado y acceso a selecciones especiales desde una sola plataforma.</p><div className="hero-actions"><Link className="btn public-cta" to="/login?signup=1">Crear mi cuenta</Link><Link className="btn public-ghost" to="/demo">Ver demostración</Link></div><div className="trust-row"><span>✓ Humedad registrada</span><span>✓ Ubicación por gaveta</span><span>✓ Inventario privado</span></div></div><div className="hero-humidor"><div className="humidor-case"><div className="case-label">CIGARROSPR</div>{[1,2,3,4].map(r=><div className="cigar-row" key={r}>{[1,2,3,4,5].map(c=><i key={c}/>)}</div>)}</div><div className="climate-card"><small>Ambiente estable</small><b>69% HR</b><span>70°F</span></div></div></section>
    <section className="public-section" id="como"><span className="eyebrow">Simple desde el primer día</span><h2>Cómo funciona</h2><div className="steps"><article><b>01</b><h3>Registra</h3><p>Añade tus cigarros por unidad o caja con marca, vitola, origen y valor.</p></article><article><b>02</b><h3>Almacena</h3><p>Asignamos cada pieza a un humidor, gaveta y espacio verificable.</p></article><article><b>03</b><h3>Disfruta</h3><p>Consulta, solicita retiro, compra o vende sin perder el control.</p></article></div></section>
    <section className="public-section plans-section" id="membresias"><span className="eyebrow">Membresías</span><h2>Escoge cómo quieres manejar tu colección</h2><div className="plan-grid">{plans.map(p=><article className={p.featured?'featured':''} key={p.name}>{p.featured&&<em>Más popular</em>}<h3>{p.name}</h3><p>{p.tag}</p><div className="plan-price"><strong>${p.price}</strong><span>/ mes</span></div><ul>{p.items.map(x=><li key={x}>✓ {x}</li>)}</ul><Link className="btn" to={`/login?signup=1&plan=${p.name.toLowerCase()}`}>Seleccionar</Link></article>)}</div></section>
    <section className="public-banner"><div><span className="eyebrow">CigarrosPR Humidor</span><h2>Menos listas. Más control.</h2><p>Ve tu colección completa, su ubicación y su valor cuando quieras.</p></div><Link className="btn public-cta" to="/login?signup=1">Comenzar</Link></section>
  </main><footer className="public-footer"><span>© 2026 CigarrosPR</span><span>Puerto Rico · Servicio para adultos 21+</span></footer>
  </div>}
