import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { money } from '../lib/i18n'
import type { BottleDetail, MembershipPlan } from '../lib/types'
import { Empty,Loading,Thumb } from '../components/ui'

const planInfo={digital:{name:'Digital',price:24.99,limit:null},reserva:{name:'Reserva',price:120,limit:40},coleccion:{name:'Colección',price:175,limit:100}}
export function Membership(){const{membership}=useAuth();const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const choose=async(plan:MembershipPlan)=>{setBusy(true);const{error}=await supabase.rpc('request_membership',{p_plan:plan});setBusy(false);setMsg(error?error.message:'Solicitud recibida. Activaremos tu membresía luego de validar el pago.');setTimeout(()=>location.reload(),1200)};return <div className="stack member-page"><span className="eyebrow">Membresía</span><h1>{membership?'Tu plan':'Escoge tu plan'}</h1>{membership&&<div className="member-plan-current"><div><small>Plan</small><b>{planInfo[membership.plan].name}</b></div><div><small>Estado</small><b>{membership.status}</b></div><div><small>Capacidad</small><b>{membership.item_limit??'Digital'}</b></div></div>}<div className="plan-grid compact">{(Object.keys(planInfo) as MembershipPlan[]).map(k=>{const p=planInfo[k];return <article key={k}><h3>{p.name}</h3><div className="plan-price"><strong>${p.price}</strong><span>/ mes</span></div><p>{p.limit?`Hasta ${p.limit} piezas o cajas en humidor.`:'Inventario digital para organizar tu colección.'}</p><button className="btn" disabled={busy||membership?.plan===k} onClick={()=>choose(k)}>{membership?.plan===k?'Plan seleccionado':'Seleccionar'}</button></article>})}</div>{msg&&<div className="info">{msg}</div>}</div>}
export function MemberHome(){const{membership}=useAuth();const[rows,setRows]=useState<BottleDetail[]|null>(null);useEffect(()=>{supabase.from('bottle_details').select('*').eq('status','in_storage').order('updated_at',{ascending:false}).then(({data})=>setRows((data??[]) as BottleDetail[]))},[]);if(rows===null)return <Loading/>;const total=rows.reduce((s,x)=>s+Number(x.purchase_price),0);return <div className="stack member-page"><div className="member-welcome"><span className="eyebrow">Mi colección</span><h1>Tu humidor, al día.</h1><p>{membership?.status==='active'?'Colección verificada y disponible.':'Completa tu membresía para activar todos los servicios.'}</p></div><div className="demo-stats"><article><small>En humidor</small><b>{rows.length}</b><span>piezas o cajas</span></article><article><small>Valor registrado</small><b>{money(total)}</b><span>compra</span></article><article><small>Plan</small><b>{membership?planInfo[membership.plan].name:'Pendiente'}</b><span>{membership?.status??'sin seleccionar'}</span></article></div><div className="row between"><h2>Recientes</h2><Link to="/collection">Ver todas</Link></div>{rows.length===0?<Empty/>:<div className="member-strip">{rows.slice(0,4).map(x=><article key={x.id}><Thumb path={x.label_photo_path}/><div><b>{x.wine_name}</b><small>{[x.producer,x.varietal].filter(Boolean).join(' · ')}</small><span>{x.rack_name?`${x.rack_name} · G${x.shelf} · E${x.position}`:'Por ubicar'}</span></div></article>)}</div>}<Link className="btn" to="/intake">Solicitar entrada</Link></div>}
export function MemberCollection(){const[rows,setRows]=useState<BottleDetail[]|null>(null);useEffect(()=>{supabase.from('bottle_details').select('*').order('updated_at',{ascending:false}).then(({data})=>setRows((data??[]) as BottleDetail[]))},[]);return <div className="stack member-page"><span className="eyebrow">Inventario privado</span><h1>Mi colección</h1>{rows===null?<Loading/>:rows.length===0?<Empty/>:<div className="member-collection">{rows.map(x=><article key={x.id}><Thumb path={x.label_photo_path}/><div><h3>{x.wine_name}</h3><p>{[x.producer,x.varietal,x.country].filter(Boolean).join(' · ')}</p><span>{x.rack_name?`${x.rack_name} · Gaveta ${x.shelf} · Espacio ${x.position}`:'Pendiente de ubicación'}</span></div><b>{money(x.purchase_price)}</b></article>)}</div>}</div>}
export function MemberIntake(){const{membership}=useAuth();const[f,setF]=useState({name:'',brand:'',vitola:'',country:'',quantity:'1',notes:''});const[msg,setMsg]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();const{error}=await supabase.from('intake_requests').insert({user_id:membership?.user_id,client_id:membership?.client_id,name:f.name,brand:f.brand||null,vitola:f.vitola||null,country:f.country||null,quantity:Number(f.quantity),notes:f.notes||null});setMsg(error?error.message:'Solicitud enviada. La validaremos físicamente al recibirla.');if(!error)setF({name:'',brand:'',vitola:'',country:'',quantity:'1',notes:''})};return <div className="stack member-page"><span className="eyebrow">Entrada verificada</span><h1>Solicitar entrada</h1><p className="muted">Esto crea una solicitud. El inventario solo se activa después del conteo y validación física de CigarrosPR.</p><form className="card stack" onSubmit={submit}><label className="field"><span>Producto</span><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><div className="grid2"><label className="field"><span>Marca</span><input value={f.brand} onChange={e=>setF({...f,brand:e.target.value})}/></label><label className="field"><span>Vitola</span><input value={f.vitola} onChange={e=>setF({...f,vitola:e.target.value})}/></label><label className="field"><span>País</span><input value={f.country} onChange={e=>setF({...f,country:e.target.value})}/></label><label className="field"><span>Cantidad</span><input type="number" min="1" max="500" value={f.quantity} onChange={e=>setF({...f,quantity:e.target.value})}/></label></div><label className="field"><span>Notas</span><textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><button className="btn">Enviar solicitud</button>{msg&&<div className="info">{msg}</div>}</form></div>}
export function MemberShop(){return <div className="stack member-page"><span className="eyebrow">Tienda CigarrosPR</span><h1>Selecciones para miembros</h1><div className="shop-empty"><b>Próximamente</b><p>Las ofertas de cigarros, cajas y lanzamientos aparecerán aquí con precio de miembro.</p></div></div>}
export function MemberAccount(){const{session,membership,profile}=useAuth();return <div className="stack member-page"><span className="eyebrow">Cuenta</span><h1>{profile?.full_name||'Mi cuenta'}</h1><div className="card stack"><div><small className="muted">Correo</small><p>{session?.user.email}</p></div><div><small className="muted">Membresía</small><p>{membership?`${planInfo[membership.plan].name} · ${membership.status}`:'Sin seleccionar'}</p></div></div><Link className="btn secondary" to="/membership">Administrar membresía</Link><button className="btn danger" onClick={()=>supabase.auth.signOut()}>Cerrar sesión</button></div>}
